apiVersion: v1
kind: Service
metadata:
  name: product1service1-extservice
spec:
  type: LoadBalancer
  selector:
    app: product1service1
  ports:
  - name: http-port
    port: 8080
    targetPort: 5000
  - name: https-port
    port: 8443
    targetPort: 5001
